### ISSUE TITLE
Modern window on fullscreen blocking content

### ISSUE THREAD

**Issue by edeuss** [macosui/macos_ui#266]
**Description**
When making the window full screen (green expand button), there seems to be a bar blocking content.

**Screenshots**
Not Fullscreen:
<img width="1430" alt="Screen Shot 2022-06-21 at 4 57 35 PM" src="https://user-images.githubusercontent.com/13773566/174915575-9fb95be9-71ff-4ee9-b038-754871bc4dfd.png">

Fullscreen:
<img width="1680" alt="Screen Shot 2022-06-21 at 4 54 44 PM" src="https://user-images.githubusercontent.com/13773566/174915742-4169f952-018d-44b0-b81a-64141cbd2cc9.png">

Fullscreen on top hover:
<img width="1680" alt="Screen Shot 2022-06-21 at 4 54 56 PM" src="https://user-images.githubusercontent.com/13773566/174915694-589a88c3-c8a8-41f9-8ef9-880c90fd264f.png">

**Logs**

<details>
  <summary>Logs</summary>

```
[✓] Flutter (Channel stable, 3.0.2, on macOS 12.4 21F79 darwin-x64, locale en-US)
    • Flutter version 3.0.2 at /Users/elias/flutter
    • Upstream repository https://github.com/flutter/flutter.git
    • Framework revision cd41fdd495 (13 days ago), 2022-06-08 09:52:13 -0700
    • Engine revision f15f824b57
    • Dart version 2.17.3
    • DevTools version 2.12.2

[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
    • Android SDK at /Users/elias/Library/Android/sdk
    • Platform android-31, build-tools 31.0.0
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 13.2.1)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • CocoaPods version 1.11.3

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 4.2)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.8+10-b944.6916264)

[✓] VS Code (version 1.68.1)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.42.0

[✓] Connected device (2 available)
    • macOS (desktop) • macos  • darwin-x64     • macOS 12.4 21F79 darwin-x64
    • Chrome (web)    • chrome • web-javascript • Google Chrome 102.0.5005.115
```

</details>

**Comment by whiplashoo** [comment]
Hi, thanks for the feedback.

This should have been fixed in #252. Running the example app looks fine, too.

Please make sure that your macos/MainFlutterWindow.swift file looks like the one in the [documentation](https://github.com/GroovinChip/macos_ui#modern-window-look)?

**Comment by edeuss** [comment]
@whiplashoo Yea I am using that exact macos/MainFlutterWindow.swift file and the issue is still persisting.

**Comment by whiplashoo** [comment]
OK, that's strange.

Could you try running the example app to see how it appears there? Do you have any other package that could be messing with the macOS window?

**Comment by edeuss** [comment]
@whiplashoo Seems like it was actually caused by ```window_manager```, When I disabled the initializiton of window manager the issue stopped.  I'll report the issue to them.
